# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_loop_rcpp <- function(n_iter, Z_samp, clust_sizes_samp, cont_samp, m_samp, u_samp, mus, nus, alphas, alpha_0, dup_upper_bound, dup_count_prior, n_prior, cont, clust_sizes, n, ab, obs_mat, record_pairs, flat, r, r_1, valid_rp, singleton_ind, rp_ind, file_labels, powers, L, num_fp, num_rp, num_field, rp_to_fp, level_cum, no_dups, valid_fp, cc, Z_members, clust_sizes_collapsed) {
    .Call(`_multilink_gibbs_loop_rcpp`, n_iter, Z_samp, clust_sizes_samp, cont_samp, m_samp, u_samp, mus, nus, alphas, alpha_0, dup_upper_bound, dup_count_prior, n_prior, cont, clust_sizes, n, ab, obs_mat, record_pairs, flat, r, r_1, valid_rp, singleton_ind, rp_ind, file_labels, powers, L, num_fp, num_rp, num_field, rp_to_fp, level_cum, no_dups, valid_fp, cc, Z_members, clust_sizes_collapsed)
}

